### ISSUE TITLE
問題を考える

### ISSUE THREAD

**Issue by sota1235** [sota1235/dark_ctf#2]
確定した問題から用意してコードとしてコミットしてしまいたい

## 決めたいこと

- [x] 何問出すのか
- [x] どんなジャンルを出すのか

## 問題候補

- [ ] Blind SQLi
- [ ] 画像のexifからflag推測問題
  - copyrightに入れるやつ
  - 座標から土地名推測させるやつ
- [ ] dark bot
  - コミュニティにいるhubotが任意コード実行できるのでそれをオマージュした何か。
  - OSコマンドインジェクションとかでうまくできないかな
- [ ] OSCi
- [ ] XPath Injection
- [ ] 暗号化
  - テキスト入れると暗号化するフォームと暗号化されたflagを渡す
  - 変換テーブル作って復号させる
- [ ] ksnctf q3オマージュ(うーにゃーエンコーダで難読化)

## 決定した問題

- [x] Reverse Polish Notation(Programming) #3 30~60分
- [x] ONION(Crypt) #5 10分
- [x] パスワードコミットしちゃった問題 #6
- [x] Kusokora is interesting #8 30分
- [x] スクリーンキャプチャ #15 10分
- [x] Basic is Secure? #11 60分
- [x] Digest is Secure!! #12 60分
- [x] Who cooked it? #13 10~30分
- [x] ディレクトリトラバーサル #9 30分
  - 末尾にNULL文字入れたら通っちゃうやつにしたい
  - 私が結局できなかったやつ
- [x] 既知平文攻撃 #14 30~60分
- [x] ROT13 10分
- [x] Emoji 30分
- [x] Thank you for playing!
- [ ] NoSQL Injection #17

**Comment by sota1235** [comment]
終わったのでclose
